version: "3.7"

networks:
  nginx-php-mysql-node:

volumes:
  db_data:
  node_modules:

services:

  #nginx service
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php81-service
      - mysql8-service
    networks:
      - nginx-php-mysql-node

  php81-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php81-container
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/project
    networks:
      - nginx-php-mysql-node

  mysql8-service:
    image: mysql:8.0
    container_name: mysql8-container
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always, on-failure, unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: parola123
      MYSQL_DATABASE: carwash
      MYSQL_USER: user
      MYSQL_PASSWORD: parola123
    networks:
      - nginx-php-mysql-node

  node-service:
    build:
      context: .
      dockerfile: ./node/Dockerfile
    container_name: node-container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/var/www/project
      - node_modules:/var/www/project/node_modules
    networks:
      - nginx-php-mysql-node